const { contextBridge, ipcRenderer } = require('electron');

const CHANNELS = Object.freeze({
  GET_SETTINGS: 'settings:get',
  SAVE_SETTINGS: 'settings:save',
  SAVE_CONNECTION: 'connections:save',
  REMOVE_CONNECTION: 'connections:remove',
  SELECT_MODEL: 'models:select',
  GET_MODEL_CATALOG: 'models:catalog',
  UPDATE_MODEL: 'models:update',
  CHECK_MODEL_CAPABILITIES: 'models:check-capabilities',
  OPEN_EXTERNAL: 'links:open-external',
  LIST_CANVAS_FILES: 'canvas:files:list',
  READ_CANVAS_FILE: 'canvas:files:read',
  DELETE_PROJECT_FILE: 'projects:files:delete',
  DELETE_PROJECT: 'projects:delete',
  DELETE_PROJECT_ASSET: 'projects:assets:delete',
  DELETE_LIBRARY_ASSET: 'assets:delete',
  CREATE_PROJECT: 'projects:create',
  RENAME_PROJECT: 'projects:rename',
  EXPORT_PROJECT: 'projects:export',
  LIST_PROJECT_DOCUMENTS: 'projects:documents:list',
  CREATE_PROJECT_DOCUMENT: 'projects:documents:create',
  OPEN_PROJECT_DOCUMENT: 'projects:documents:open',
  GET_PROJECT_ASSETS: 'projects:assets:list',
  GET_PROJECT_ASSET: 'projects:assets:get',
  GET_LIBRARY_ASSET: 'assets:get',
  SAVE_LIBRARY_ASSET: 'assets:save',
  ATTACH_PROJECT_ASSET: 'projects:assets:attach',
  SAVE_PROJECT_ASSET: 'projects:assets:save',
  HIDE_CANVAS_PREVIEW: 'canvas:preview:hide',
  MANAGE_CANVAS_DEVICES: 'canvas:devices:manage',
  CLOSE_CANVAS: 'canvases:close',
  LIST_CANVAS_INPUTS: 'canvas:inputs:list',
  RETRY_CANVAS_INPUT: 'canvas:inputs:retry',
  SEND_MESSAGE: 'chat:send',
  STOP_AGENT: 'chat:stop',
  CLEAR_CHAT: 'chat:clear',
  GET_CHAT: 'chat:get',
  LIST_CHATS: 'chat:list',
  OPEN_CHAT: 'chat:open',
  AGENT_EVENT: 'agent:event',
  LIST_ASSETS: 'assets:list',
  LIST_MEDIA_JOBS: 'media:jobs:list',
  DELETE_MEDIA_JOB: 'media:jobs:delete',
  RETRY_MEDIA_JOB: 'media:jobs:retry',
  LIST_CANVASES: 'canvases:list',
  CREATE_CANVAS: 'canvases:create',
  OPEN_CANVAS: 'canvases:open',
  SAVE_CANVAS: 'canvases:save',
  EXPORT_CANVAS: 'canvases:export',
  ADD_ASSET_TO_CANVAS: 'canvas:add-asset',
  UNDO_CANVAS: 'canvas:undo',
  SET_CANVAS_BOUNDS: 'canvas:set-bounds',
  LIST_LITELLM_MODELS: 'litellm:models:list',
  TEST_LITELLM_CHAT: 'litellm:probe:chat',
  TEST_LITELLM_IMAGE: 'litellm:probe:image',
  LIST_INSTALLED_SKILLS: 'skills:list-installed',
});

function createBridge({ contextBridge: bridge, ipcRenderer: ipc }) {
  const api = Object.freeze({
    getSettings: () => ipc.invoke(CHANNELS.GET_SETTINGS),
    saveConnection: (input) => ipc.invoke(CHANNELS.SAVE_CONNECTION, input),
    removeConnection: (id) => ipc.invoke(CHANNELS.REMOVE_CONNECTION, id),
    selectModel: (input) => ipc.invoke(CHANNELS.SELECT_MODEL, input),
    getModelCatalog: () => ipc.invoke(CHANNELS.GET_MODEL_CATALOG),
    updateModel: (input) => ipc.invoke(CHANNELS.UPDATE_MODEL, input),
    checkModelCapabilities: (input) => ipc.invoke(CHANNELS.CHECK_MODEL_CAPABILITIES, input),
    openExternal: (url) => ipc.invoke(CHANNELS.OPEN_EXTERNAL, url),
    listCanvasFiles: (id) => ipc.invoke(CHANNELS.LIST_CANVAS_FILES, id),
    readCanvasFile: (id, input) => ipc.invoke(CHANNELS.READ_CANVAS_FILE, id, input),
    deleteProjectFile: (id, input) => ipc.invoke(CHANNELS.DELETE_PROJECT_FILE, id, input),
    deleteProject: (id) => ipc.invoke(CHANNELS.DELETE_PROJECT, id),
    deleteProjectAsset: (id, assetId) => ipc.invoke(CHANNELS.DELETE_PROJECT_ASSET, id, assetId),
    deleteLibraryAsset: (assetId) => ipc.invoke(CHANNELS.DELETE_LIBRARY_ASSET, assetId),
    createProject: (input) => ipc.invoke(CHANNELS.CREATE_PROJECT, input),
    renameProject: (id, input) => ipc.invoke(CHANNELS.RENAME_PROJECT, id, input),
    exportProject: (id) => ipc.invoke(CHANNELS.EXPORT_PROJECT, id),
    listProjectDocuments: (id) => ipc.invoke(CHANNELS.LIST_PROJECT_DOCUMENTS, id),
    createProjectDocument: (id, input) => ipc.invoke(CHANNELS.CREATE_PROJECT_DOCUMENT, id, input),
    openProjectDocument: (id, documentPath) => ipc.invoke(CHANNELS.OPEN_PROJECT_DOCUMENT, id, documentPath),
    getProjectAssets: (id) => ipc.invoke(CHANNELS.GET_PROJECT_ASSETS, id),
    getProjectAsset: (id, assetId) => ipc.invoke(CHANNELS.GET_PROJECT_ASSET, id, assetId),
    getLibraryAsset: (assetId) => ipc.invoke(CHANNELS.GET_LIBRARY_ASSET, assetId),
    saveLibraryAsset: (assetId) => ipc.invoke(CHANNELS.SAVE_LIBRARY_ASSET, assetId),
    attachProjectAsset: (id, assetId) => ipc.invoke(CHANNELS.ATTACH_PROJECT_ASSET, id, assetId),
    saveProjectAsset: (id, assetId) => ipc.invoke(CHANNELS.SAVE_PROJECT_ASSET, id, assetId),
    hideCanvasPreview: () => ipc.invoke(CHANNELS.HIDE_CANVAS_PREVIEW),
    manageCanvasDevices: (id) => ipc.invoke(CHANNELS.MANAGE_CANVAS_DEVICES, id),
    closeCanvas: (id) => ipc.invoke(CHANNELS.CLOSE_CANVAS, id),
    listCanvasInputs: () => ipc.invoke(CHANNELS.LIST_CANVAS_INPUTS),
    retryCanvasInput: (id) => ipc.invoke(CHANNELS.RETRY_CANVAS_INPUT, id),
    listLiteLLMModels: () => ipc.invoke(CHANNELS.LIST_LITELLM_MODELS),
    testLiteLLMChat: (model) => ipc.invoke(CHANNELS.TEST_LITELLM_CHAT, model),
    testLiteLLMImage: (model) => ipc.invoke(CHANNELS.TEST_LITELLM_IMAGE, model),
    listInstalledSkills: () => ipc.invoke(CHANNELS.LIST_INSTALLED_SKILLS),
    saveSettings: (settings) => ipc.invoke(CHANNELS.SAVE_SETTINGS, settings),
    sendMessage: (text, options) => ipc.invoke(CHANNELS.SEND_MESSAGE, text, options),
    stopAgent: () => ipc.invoke(CHANNELS.STOP_AGENT),
    clearChat: () => ipc.invoke(CHANNELS.CLEAR_CHAT),
    getCurrentChat: () => ipc.invoke(CHANNELS.GET_CHAT),
    listChats: () => ipc.invoke(CHANNELS.LIST_CHATS),
    openChat: (id) => ipc.invoke(CHANNELS.OPEN_CHAT, id),
    listAssets: () => ipc.invoke(CHANNELS.LIST_ASSETS),
    listMediaJobs: () => ipc.invoke(CHANNELS.LIST_MEDIA_JOBS),
    deleteMediaJob: (id) => ipc.invoke(CHANNELS.DELETE_MEDIA_JOB, id),
    retryMediaJob: (id) => ipc.invoke(CHANNELS.RETRY_MEDIA_JOB, id),
    listCanvases: () => ipc.invoke(CHANNELS.LIST_CANVASES),
    createCanvas: (title, kits = []) => ipc.invoke(CHANNELS.CREATE_CANVAS, title, kits),
    openCanvas: (id) => ipc.invoke(CHANNELS.OPEN_CANVAS, id),
    saveCanvas: (id) => ipc.invoke(CHANNELS.SAVE_CANVAS, id),
    exportCanvas: (id) => ipc.invoke(CHANNELS.EXPORT_CANVAS, id),
    addAssetToCanvas: (id, options) => ipc.invoke(CHANNELS.ADD_ASSET_TO_CANVAS, id, options),
    undoCanvas: (id) => ipc.invoke(CHANNELS.UNDO_CANVAS, id),
    setCanvasBounds: (bounds) => ipc.send(CHANNELS.SET_CANVAS_BOUNDS, bounds),
    onAgentEvent(callback) {
      if (typeof callback !== 'function') throw new TypeError('Event callback must be a function.');
      const listener = (_event, payload) => callback(payload);
      ipc.on(CHANNELS.AGENT_EVENT, listener);
      return () => ipc.removeListener(CHANNELS.AGENT_EVENT, listener);
    },
  });

  bridge.exposeInMainWorld('easelClient', api);
  return api;
}

createBridge({ contextBridge, ipcRenderer });

module.exports = { createBridge };
