function setStatus(element, message, isError = false) {
  element.textContent = message;
  element.classList.toggle('error', isError);
  element.setAttribute('role', isError ? 'alert' : 'status');
  element.setAttribute('aria-live', isError ? 'assertive' : 'polite');
}

function normalizeResultSource(value) {
  if (typeof value !== 'string') return null;
  if (/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/]+={0,2}$/i.test(value)) return value;
  try {
    const url = new URL(value);
    return ['http:', 'https:'].includes(url.protocol) ? url.toString() : null;
  } catch {
    return null;
  }
}

function resultSummary(count) {
  return `Generated ${count} image${count === 1 ? '' : 's'}.`;
}

async function handleGenerationSubmit({ client, document, promptInput, submitButton, statusElement, resultsElement, ...options }) {
  submitButton.disabled = true;
  setStatus(statusElement, 'Generating images…');
  try {
    const images = await client.generateImages({
      baseUrl: options.baseUrlInput?.value,
      apiKey: options.apiKeyInput?.value,
      model: options.modelInput?.value,
      size: options.sizeInput?.value,
      prompt: promptInput.value,
    });
    const cards = images.flatMap((source, index) => {
      const safeSource = normalizeResultSource(source);
      if (!safeSource) return [];
      const card = document.createElement('article');
      card.className = 'result-card';
      card.setAttribute('role', 'listitem');
      const image = document.createElement('img');
      image.src = safeSource;
      image.alt = `${promptInput.value.trim()} ${index + 1}`;
      card.append(image);
      return [card];
    });
    resultsElement.replaceChildren(...cards);
    setStatus(statusElement, resultSummary(cards.length));
    return cards.length;
  } catch (error) {
    setStatus(statusElement, error instanceof Error ? error.message : 'Image generation failed.', true);
    throw error;
  } finally {
    submitButton.disabled = false;
  }
}

function appendTextMessage(document, messagesElement, role, text) {
  const message = document.createElement('article');
  message.className = `message ${role}`;
  message.textContent = text;
  messagesElement.append(message);
  return message;
}

function renderAgentEvent({ document, messagesElement, imagesElement, event, statusElement }) {
  if (!event || typeof event.type !== 'string') return;
  if (event.type === 'assistant' && typeof event.text === 'string' && event.text) {
    appendTextMessage(document, messagesElement, 'assistant', event.text);
    setStatus(statusElement, '');
    return;
  }
  if (event.type === 'tool-start') {
    setStatus(statusElement, 'Working with Easel…');
    return;
  }
  if (event.type === 'image') {
    if (typeof event.data !== 'string' || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(event.data)) return;
    if (!['image/png', 'image/jpeg', 'image/webp'].includes(event.mimeType)) return;
    const card = document.createElement('figure');
    card.className = 'image-result';
    const image = document.createElement('img');
    image.src = `data:${event.mimeType};base64,${event.data}`;
    image.alt = 'Image generated by Easel';
    card.append(image);
    imagesElement.append(card);
    return;
  }
  if (event.type === 'canvas') {
    setStatus(statusElement, `Canvas updated: ${String(event.title || 'Easel Canvas')}`);
    return;
  }
  if (event.type === 'error' && typeof event.message === 'string') {
    setStatus(statusElement, event.message, true);
  }
}

async function handleSettingsSubmit({ client, fields, statusElement }) {
  setStatus(statusElement, 'Saving settings…');
  try {
    const result = await client.saveSettings({
      easelBaseUrl: fields.easelBaseUrl.value,
      easelApiKey: fields.easelApiKey.value,
      clearEaselApiKey: fields.clearEaselApiKey.checked === true,
      litellmBaseUrl: fields.litellmBaseUrl.value,
      litellmModel: fields.litellmModel.value,
      litellmApiKey: fields.litellmApiKey.value,
      clearLiteLLMApiKey: fields.clearLiteLLMApiKey.checked === true,
    });
    fields.easelApiKey.value = '';
    fields.litellmApiKey.value = '';
    fields.clearEaselApiKey.checked = false;
    fields.clearLiteLLMApiKey.checked = false;
    fields.easelApiKey.placeholder = result.hasEaselApiKey ? 'Saved securely' : 'Optional';
    fields.litellmApiKey.placeholder = result.hasLiteLLMApiKey ? 'Saved securely' : 'Optional';
    setStatus(statusElement, 'Settings saved.');
    return result;
  } catch (error) {
    setStatus(statusElement, error instanceof Error ? error.message : 'Could not save settings.', true);
    throw error;
  }
}

async function handleChatSubmit({ client, document, input, button, statusElement, messagesElement }) {
  const text = input.value.trim();
  if (!text) return;
  button.disabled = true;
  appendTextMessage(document, messagesElement, 'user', text);
  setStatus(statusElement, 'Thinking…');
  try {
    const result = await client.sendMessage(text);
    input.value = '';
    if (!result?.events) setStatus(statusElement, '');
    return result;
  } catch (error) {
    setStatus(statusElement, error instanceof Error ? error.message : 'The message could not be sent.', true);
    throw error;
  } finally {
    button.disabled = false;
  }
}

function wireRenderer({ document, client }) {
  const fields = {
    easelBaseUrl: document.getElementById('easel-url'),
    easelApiKey: document.getElementById('easel-key'),
    clearEaselApiKey: document.getElementById('clear-easel-key'),
    litellmBaseUrl: document.getElementById('litellm-url'),
    litellmModel: document.getElementById('litellm-model'),
    litellmApiKey: document.getElementById('litellm-key'),
    clearLiteLLMApiKey: document.getElementById('clear-litellm-key'),
  };
  const settingsForm = document.getElementById('settings-form');
  const settingsStatus = document.getElementById('settings-status');
  const chatForm = document.getElementById('chat-form');
  const messageInput = document.getElementById('message');
  const sendButton = document.getElementById('send');
  const statusElement = document.getElementById('status');
  const messagesElement = document.getElementById('messages');
  const imagesElement = document.getElementById('images');

  settingsForm.addEventListener('submit', async (event) => {
    event.preventDefault();
    try {
      await handleSettingsSubmit({ client, fields, statusElement: settingsStatus });
    } catch {}
  });
  chatForm.addEventListener('submit', async (event) => {
    event.preventDefault();
    try {
      await handleChatSubmit({
        client,
        document,
        input: messageInput,
        button: sendButton,
        statusElement,
        messagesElement,
      });
    } catch {}
  });

  const unsubscribe = client.onAgentEvent((event) => {
    renderAgentEvent({ document, messagesElement, imagesElement, event, statusElement });
  });
  client.getSettings().then((settings) => {
    fields.easelBaseUrl.value = settings.easelBaseUrl;
    fields.litellmBaseUrl.value = settings.litellmBaseUrl;
    fields.litellmModel.value = settings.litellmModel;
    fields.easelApiKey.placeholder = settings.hasEaselApiKey ? 'Saved securely' : 'Optional';
    fields.litellmApiKey.placeholder = settings.hasLiteLLMApiKey ? 'Saved securely' : 'Optional';
  }).catch((error) => setStatus(settingsStatus, error?.message || 'Could not load settings.', true));

  return { dispose: unsubscribe };
}

if (typeof module !== 'undefined') {
  module.exports = {
    appendTextMessage,
    handleGenerationSubmit,
    normalizeResultSource,
    resultSummary,
    handleChatSubmit,
    handleSettingsSubmit,
    renderAgentEvent,
    setStatus,
    wireRenderer,
  };
}

if (typeof window !== 'undefined' && window.document && window.easelClient) {
  wireRenderer({ document: window.document, client: window.easelClient });
}
